### ISSUE TITLE
[功能需求] mailgun

### ISSUE THREAD

**Issue by BlueNoob** [mouday/domain-admin-web#14]
## mailgun
发邮件处，使用两种方式
1.配置SMTP信息，SMTP发邮件
2.配置mailgun信息，调用mailgun去发

**Comment by mouday** [comment]
mailgun是第三方服务吧，是否可以考虑使用webhook触发呢？

**Comment by BlueNoob** [comment]
> mailgun是第三方服务吧，是否可以考虑使用webhook触发呢？

### API code sample
[https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-with-smtp-or-api](https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-with-smtp-or-api)
```
def send_simple_message():
    return requests.post(
        "https://api.mailgun.net/v3/YOUR_DOMAIN_NAME/messages",
        auth=("api", "YOUR_API_KEY"),
        data={"from": "Excited User <mailgun@YOUR_DOMAIN_NAME>",
              "to": ["bar@example.com", "YOU@YOUR_DOMAIN_NAME"],
              "subject": "Hello",
              "text": "Testing some Mailgun awesomness!"})
```

**Comment by mouday** [comment]
这个格式和Resend很像
https://domain-admin.readthedocs.io/zh-cn/latest/manual/notify.html#webhookresend

<img width="756" alt="image" src="https://github.com/mouday/domain-admin-web/assets/24365682/7a2afc29-edf2-42c6-8f28-63fd131695fa">

**Comment by BlueNoob** [comment]
就是调用API进行发件，有个界面配置凭证就好了
API URL
API凭证
就是通用的了。
API跟webhook方式还是不一样的

**Comment by BlueNoob** [comment]
把auth放在请求体里，可实现
